### ISSUE TITLE
JournalVouchersService not working ?!

### ISSUE THREAD

**Issue by ametwaly** [SAP/SAP-Business-One-Service-Layer-SDK#3]
I was trying to add a new JournalVoucher it's giving me this error :
feign.FeignException: status 400 reading JournalVouchersService#add(JournalVouchersService_AddParam); content:
{
   "error" : {
      "code" : -1005,
      "message" : {
         "lang" : "en-us",
         "value" : "Data  not found"
      }
   }
}

**Comment by SebastianWolf-SAP** [comment]
Dear ametwaly,

I'm sorry to tell you that this project is no longer maintained. As we will archive it now, we also need to close open issues.

Thank you for your understanding and best regards,

Sebastian (SAP Open Source Program Office)
