### ISSUE TITLE
Install - use tutorial

### ISSUE THREAD

**Issue by gms0812** [SAP/SAP-Business-One-Service-Layer-SDK#7]
Hi, how are you.
I'm new in git, maven, spring boot, and using the SAP Service Layer, so i don't understand how to use this in my project.
Is there any way that you could provide a tutorial or some kind of guide for dummies to understand how to "compile and add" this to a java project so i can use it and test it as you do in de README?

Pleaseeeeee help meeee

**Comment by SebastianWolf-SAP** [comment]
Dear gms0812,

I'm sorry to tell you that this project is no longer maintained. As we will archive it now, we also need to close open issues.

Thank you for your understanding and best regards,

Sebastian (SAP Open Source Program Office)
